server:
  port: 9005
spring:
  application:
    name: order-springcloud-sentinel9001
  cloud:
    consul:
      enabled: # true #//是否启用consul
        host: localhost #// consul server的ip地址
        port: 8500 #// consul运行的端口号
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
feign:
  sentinel:
    enabled: true