server:
  port: 8002

spring:
  application:
    name: payment-springcloud
  datasource:
    url: jdbc:mysql://10.181.3.75:3307/ferny-admin-uat?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: Qoros111
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  cloud:
    consul:
      enabled: # true #//是否启用consul
        host: localhost #// consul server的ip地址
        port: 8500 #// consul运行的端口号

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
