server:
  port: 80
spring:
  application:
    name: oderment-springcloude
  datasource:
    url: jdbc:mysql://10.181.3.75:3307/ferny-admin-uat?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: Qoros111
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml

eureka:
  client:
    registerWithEureka: true #不把自己作为一个客户端注册到自己身上
    fetchRegistry: true #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注册了
    serviceUrl:
      defaultZone: http://eureka8762.com:8762/eureka,http://eureka8761.com:8761/eureka
