

server:
  port: 8762
spring:
  application:
    name: eureka-springcloud-8762
eureka:
  instance:
    hostname: eureka8762.com
  server:
    enable-self-preservation: false  #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #设置清理间隔（单位：毫秒 默认是60*1000）
  client:
    registerWithEureka: false #不把自己作为一个客户端注册到自己身上
    fetchRegistry: false #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注册了
    serviceUrl:
      defaultZone: http://eureka8761.com:8761/eureka
